# @generated by generate_proto_mypy_stubs.py.  Do not edit!
import sys
from google.protobuf.any_pb2 import (
    Any as google___protobuf___any_pb2___Any,
)

from google.protobuf.descriptor import (
    Descriptor as google___protobuf___descriptor___Descriptor,
    FileDescriptor as google___protobuf___descriptor___FileDescriptor,
)

from google.protobuf.internal.containers import (
    RepeatedCompositeFieldContainer as google___protobuf___internal___containers___RepeatedCompositeFieldContainer,
)

from google.protobuf.message import (
    Message as google___protobuf___message___Message,
)

from buildgrid._protos.google.rpc.status_pb2 import (
    Status as google___rpc___status_pb2___Status,
)

from typing import (
    Iterable as typing___Iterable,
    Optional as typing___Optional,
    Text as typing___Text,
)

from typing_extensions import (
    Literal as typing_extensions___Literal,
)


builtin___bool = bool
builtin___bytes = bytes
builtin___float = float
builtin___int = int


DESCRIPTOR: google___protobuf___descriptor___FileDescriptor = ...

class Operation(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    name: typing___Text = ...
    done: builtin___bool = ...

    @property
    def metadata(self) -> google___protobuf___any_pb2___Any: ...

    @property
    def error(self) -> google___rpc___status_pb2___Status: ...

    @property
    def response(self) -> google___protobuf___any_pb2___Any: ...

    def __init__(self,
        *,
        name : typing___Optional[typing___Text] = None,
        metadata : typing___Optional[google___protobuf___any_pb2___Any] = None,
        done : typing___Optional[builtin___bool] = None,
        error : typing___Optional[google___rpc___status_pb2___Status] = None,
        response : typing___Optional[google___protobuf___any_pb2___Any] = None,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions___Literal[u"error",b"error",u"metadata",b"metadata",u"response",b"response",u"result",b"result"]) -> builtin___bool: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"done",b"done",u"error",b"error",u"metadata",b"metadata",u"name",b"name",u"response",b"response",u"result",b"result"]) -> None: ...
    def WhichOneof(self, oneof_group: typing_extensions___Literal[u"result",b"result"]) -> typing_extensions___Literal["error","response"]: ...
type___Operation = Operation

class GetOperationRequest(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    name: typing___Text = ...

    def __init__(self,
        *,
        name : typing___Optional[typing___Text] = None,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"name",b"name"]) -> None: ...
type___GetOperationRequest = GetOperationRequest

class ListOperationsRequest(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    name: typing___Text = ...
    filter: typing___Text = ...
    page_size: builtin___int = ...
    page_token: typing___Text = ...

    def __init__(self,
        *,
        name : typing___Optional[typing___Text] = None,
        filter : typing___Optional[typing___Text] = None,
        page_size : typing___Optional[builtin___int] = None,
        page_token : typing___Optional[typing___Text] = None,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"filter",b"filter",u"name",b"name",u"page_size",b"page_size",u"page_token",b"page_token"]) -> None: ...
type___ListOperationsRequest = ListOperationsRequest

class ListOperationsResponse(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    next_page_token: typing___Text = ...

    @property
    def operations(self) -> google___protobuf___internal___containers___RepeatedCompositeFieldContainer[type___Operation]: ...

    def __init__(self,
        *,
        operations : typing___Optional[typing___Iterable[type___Operation]] = None,
        next_page_token : typing___Optional[typing___Text] = None,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"next_page_token",b"next_page_token",u"operations",b"operations"]) -> None: ...
type___ListOperationsResponse = ListOperationsResponse

class CancelOperationRequest(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    name: typing___Text = ...

    def __init__(self,
        *,
        name : typing___Optional[typing___Text] = None,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"name",b"name"]) -> None: ...
type___CancelOperationRequest = CancelOperationRequest

class DeleteOperationRequest(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    name: typing___Text = ...

    def __init__(self,
        *,
        name : typing___Optional[typing___Text] = None,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"name",b"name"]) -> None: ...
type___DeleteOperationRequest = DeleteOperationRequest
