# @generated by generate_proto_mypy_stubs.py.  Do not edit!
import sys
from buildgrid._protos.build.bazel.remote.execution.v2.remote_execution_pb2 import (
    Digest as build___bazel___remote___execution___v2___remote_execution_pb2___Digest,
)

from google.protobuf.descriptor import (
    Descriptor as google___protobuf___descriptor___Descriptor,
    FileDescriptor as google___protobuf___descriptor___FileDescriptor,
)

from google.protobuf.internal.containers import (
    RepeatedScalarFieldContainer as google___protobuf___internal___containers___RepeatedScalarFieldContainer,
)

from google.protobuf.message import (
    Message as google___protobuf___message___Message,
)

from typing import (
    Iterable as typing___Iterable,
    Optional as typing___Optional,
    Text as typing___Text,
)

from typing_extensions import (
    Literal as typing_extensions___Literal,
)


builtin___bool = bool
builtin___bytes = bytes
builtin___float = float
builtin___int = int


DESCRIPTOR: google___protobuf___descriptor___FileDescriptor = ...

class GetReferenceRequest(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    instance_name: typing___Text = ...
    key: typing___Text = ...

    def __init__(self,
        *,
        instance_name : typing___Optional[typing___Text] = None,
        key : typing___Optional[typing___Text] = None,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"instance_name",b"instance_name",u"key",b"key"]) -> None: ...
type___GetReferenceRequest = GetReferenceRequest

class GetReferenceResponse(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...

    @property
    def digest(self) -> build___bazel___remote___execution___v2___remote_execution_pb2___Digest: ...

    def __init__(self,
        *,
        digest : typing___Optional[build___bazel___remote___execution___v2___remote_execution_pb2___Digest] = None,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions___Literal[u"digest",b"digest"]) -> builtin___bool: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"digest",b"digest"]) -> None: ...
type___GetReferenceResponse = GetReferenceResponse

class UpdateReferenceRequest(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    instance_name: typing___Text = ...
    keys: google___protobuf___internal___containers___RepeatedScalarFieldContainer[typing___Text] = ...

    @property
    def digest(self) -> build___bazel___remote___execution___v2___remote_execution_pb2___Digest: ...

    def __init__(self,
        *,
        instance_name : typing___Optional[typing___Text] = None,
        keys : typing___Optional[typing___Iterable[typing___Text]] = None,
        digest : typing___Optional[build___bazel___remote___execution___v2___remote_execution_pb2___Digest] = None,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions___Literal[u"digest",b"digest"]) -> builtin___bool: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"digest",b"digest",u"instance_name",b"instance_name",u"keys",b"keys"]) -> None: ...
type___UpdateReferenceRequest = UpdateReferenceRequest

class UpdateReferenceResponse(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...

    def __init__(self,
        ) -> None: ...
type___UpdateReferenceResponse = UpdateReferenceResponse

class StatusRequest(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    instance_name: typing___Text = ...

    def __init__(self,
        *,
        instance_name : typing___Optional[typing___Text] = None,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"instance_name",b"instance_name"]) -> None: ...
type___StatusRequest = StatusRequest

class StatusResponse(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    allow_updates: builtin___bool = ...

    def __init__(self,
        *,
        allow_updates : typing___Optional[builtin___bool] = None,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"allow_updates",b"allow_updates"]) -> None: ...
type___StatusResponse = StatusResponse
