# @generated by generate_proto_mypy_stubs.py.  Do not edit!
import sys
from buildgrid._protos.google.devtools.remoteworkers.v1test2.worker_pb2 import (
    Worker as google___devtools___remoteworkers___v1test2___worker_pb2___Worker,
)

from google.protobuf.any_pb2 import (
    Any as google___protobuf___any_pb2___Any,
)

from google.protobuf.descriptor import (
    Descriptor as google___protobuf___descriptor___Descriptor,
    EnumDescriptor as google___protobuf___descriptor___EnumDescriptor,
    FileDescriptor as google___protobuf___descriptor___FileDescriptor,
)

from google.protobuf.field_mask_pb2 import (
    FieldMask as google___protobuf___field_mask_pb2___FieldMask,
)

from google.protobuf.internal.containers import (
    RepeatedCompositeFieldContainer as google___protobuf___internal___containers___RepeatedCompositeFieldContainer,
)

from google.protobuf.internal.enum_type_wrapper import (
    _EnumTypeWrapper as google___protobuf___internal___enum_type_wrapper____EnumTypeWrapper,
)

from google.protobuf.message import (
    Message as google___protobuf___message___Message,
)

from google.protobuf.timestamp_pb2 import (
    Timestamp as google___protobuf___timestamp_pb2___Timestamp,
)

from buildgrid._protos.google.rpc.status_pb2 import (
    Status as google___rpc___status_pb2___Status,
)

from typing import (
    Iterable as typing___Iterable,
    NewType as typing___NewType,
    Optional as typing___Optional,
    Text as typing___Text,
    cast as typing___cast,
)

from typing_extensions import (
    Literal as typing_extensions___Literal,
)


builtin___bool = bool
builtin___bytes = bytes
builtin___float = float
builtin___int = int


DESCRIPTOR: google___protobuf___descriptor___FileDescriptor = ...

BotStatusValue = typing___NewType('BotStatusValue', builtin___int)
type___BotStatusValue = BotStatusValue
BotStatus: _BotStatus
class _BotStatus(google___protobuf___internal___enum_type_wrapper____EnumTypeWrapper[BotStatusValue]):
    DESCRIPTOR: google___protobuf___descriptor___EnumDescriptor = ...
    BOT_STATUS_UNSPECIFIED = typing___cast(BotStatusValue, 0)
    OK = typing___cast(BotStatusValue, 1)
    UNHEALTHY = typing___cast(BotStatusValue, 2)
    HOST_REBOOTING = typing___cast(BotStatusValue, 3)
    BOT_TERMINATING = typing___cast(BotStatusValue, 4)
BOT_STATUS_UNSPECIFIED = typing___cast(BotStatusValue, 0)
OK = typing___cast(BotStatusValue, 1)
UNHEALTHY = typing___cast(BotStatusValue, 2)
HOST_REBOOTING = typing___cast(BotStatusValue, 3)
BOT_TERMINATING = typing___cast(BotStatusValue, 4)
type___BotStatus = BotStatus

LeaseStateValue = typing___NewType('LeaseStateValue', builtin___int)
type___LeaseStateValue = LeaseStateValue
LeaseState: _LeaseState
class _LeaseState(google___protobuf___internal___enum_type_wrapper____EnumTypeWrapper[LeaseStateValue]):
    DESCRIPTOR: google___protobuf___descriptor___EnumDescriptor = ...
    LEASE_STATE_UNSPECIFIED = typing___cast(LeaseStateValue, 0)
    PENDING = typing___cast(LeaseStateValue, 1)
    ACTIVE = typing___cast(LeaseStateValue, 2)
    COMPLETED = typing___cast(LeaseStateValue, 4)
    CANCELLED = typing___cast(LeaseStateValue, 5)
LEASE_STATE_UNSPECIFIED = typing___cast(LeaseStateValue, 0)
PENDING = typing___cast(LeaseStateValue, 1)
ACTIVE = typing___cast(LeaseStateValue, 2)
COMPLETED = typing___cast(LeaseStateValue, 4)
CANCELLED = typing___cast(LeaseStateValue, 5)
type___LeaseState = LeaseState

class BotSession(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    name: typing___Text = ...
    bot_id: typing___Text = ...
    status: type___BotStatusValue = ...
    version: typing___Text = ...

    @property
    def worker(self) -> google___devtools___remoteworkers___v1test2___worker_pb2___Worker: ...

    @property
    def leases(self) -> google___protobuf___internal___containers___RepeatedCompositeFieldContainer[type___Lease]: ...

    @property
    def expire_time(self) -> google___protobuf___timestamp_pb2___Timestamp: ...

    def __init__(self,
        *,
        name : typing___Optional[typing___Text] = None,
        bot_id : typing___Optional[typing___Text] = None,
        status : typing___Optional[type___BotStatusValue] = None,
        worker : typing___Optional[google___devtools___remoteworkers___v1test2___worker_pb2___Worker] = None,
        leases : typing___Optional[typing___Iterable[type___Lease]] = None,
        expire_time : typing___Optional[google___protobuf___timestamp_pb2___Timestamp] = None,
        version : typing___Optional[typing___Text] = None,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions___Literal[u"expire_time",b"expire_time",u"worker",b"worker"]) -> builtin___bool: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"bot_id",b"bot_id",u"expire_time",b"expire_time",u"leases",b"leases",u"name",b"name",u"status",b"status",u"version",b"version",u"worker",b"worker"]) -> None: ...
type___BotSession = BotSession

class Lease(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    id: typing___Text = ...
    state: type___LeaseStateValue = ...
    assignment: typing___Text = ...

    @property
    def payload(self) -> google___protobuf___any_pb2___Any: ...

    @property
    def result(self) -> google___protobuf___any_pb2___Any: ...

    @property
    def status(self) -> google___rpc___status_pb2___Status: ...

    @property
    def requirements(self) -> google___devtools___remoteworkers___v1test2___worker_pb2___Worker: ...

    @property
    def expire_time(self) -> google___protobuf___timestamp_pb2___Timestamp: ...

    @property
    def inline_assignment(self) -> google___protobuf___any_pb2___Any: ...

    def __init__(self,
        *,
        id : typing___Optional[typing___Text] = None,
        payload : typing___Optional[google___protobuf___any_pb2___Any] = None,
        result : typing___Optional[google___protobuf___any_pb2___Any] = None,
        state : typing___Optional[type___LeaseStateValue] = None,
        status : typing___Optional[google___rpc___status_pb2___Status] = None,
        requirements : typing___Optional[google___devtools___remoteworkers___v1test2___worker_pb2___Worker] = None,
        expire_time : typing___Optional[google___protobuf___timestamp_pb2___Timestamp] = None,
        assignment : typing___Optional[typing___Text] = None,
        inline_assignment : typing___Optional[google___protobuf___any_pb2___Any] = None,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions___Literal[u"expire_time",b"expire_time",u"inline_assignment",b"inline_assignment",u"payload",b"payload",u"requirements",b"requirements",u"result",b"result",u"status",b"status"]) -> builtin___bool: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"assignment",b"assignment",u"expire_time",b"expire_time",u"id",b"id",u"inline_assignment",b"inline_assignment",u"payload",b"payload",u"requirements",b"requirements",u"result",b"result",u"state",b"state",u"status",b"status"]) -> None: ...
type___Lease = Lease

class AdminTemp(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    CommandValue = typing___NewType('CommandValue', builtin___int)
    type___CommandValue = CommandValue
    Command: _Command
    class _Command(google___protobuf___internal___enum_type_wrapper____EnumTypeWrapper[AdminTemp.CommandValue]):
        DESCRIPTOR: google___protobuf___descriptor___EnumDescriptor = ...
        UNSPECIFIED = typing___cast(AdminTemp.CommandValue, 0)
        BOT_UPDATE = typing___cast(AdminTemp.CommandValue, 1)
        BOT_RESTART = typing___cast(AdminTemp.CommandValue, 2)
        BOT_TERMINATE = typing___cast(AdminTemp.CommandValue, 3)
        HOST_RESTART = typing___cast(AdminTemp.CommandValue, 4)
    UNSPECIFIED = typing___cast(AdminTemp.CommandValue, 0)
    BOT_UPDATE = typing___cast(AdminTemp.CommandValue, 1)
    BOT_RESTART = typing___cast(AdminTemp.CommandValue, 2)
    BOT_TERMINATE = typing___cast(AdminTemp.CommandValue, 3)
    HOST_RESTART = typing___cast(AdminTemp.CommandValue, 4)
    type___Command = Command

    command: type___AdminTemp.CommandValue = ...
    arg: typing___Text = ...

    def __init__(self,
        *,
        command : typing___Optional[type___AdminTemp.CommandValue] = None,
        arg : typing___Optional[typing___Text] = None,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"arg",b"arg",u"command",b"command"]) -> None: ...
type___AdminTemp = AdminTemp

class CreateBotSessionRequest(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    parent: typing___Text = ...

    @property
    def bot_session(self) -> type___BotSession: ...

    def __init__(self,
        *,
        parent : typing___Optional[typing___Text] = None,
        bot_session : typing___Optional[type___BotSession] = None,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions___Literal[u"bot_session",b"bot_session"]) -> builtin___bool: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"bot_session",b"bot_session",u"parent",b"parent"]) -> None: ...
type___CreateBotSessionRequest = CreateBotSessionRequest

class UpdateBotSessionRequest(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    name: typing___Text = ...

    @property
    def bot_session(self) -> type___BotSession: ...

    @property
    def update_mask(self) -> google___protobuf___field_mask_pb2___FieldMask: ...

    def __init__(self,
        *,
        name : typing___Optional[typing___Text] = None,
        bot_session : typing___Optional[type___BotSession] = None,
        update_mask : typing___Optional[google___protobuf___field_mask_pb2___FieldMask] = None,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions___Literal[u"bot_session",b"bot_session",u"update_mask",b"update_mask"]) -> builtin___bool: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"bot_session",b"bot_session",u"name",b"name",u"update_mask",b"update_mask"]) -> None: ...
type___UpdateBotSessionRequest = UpdateBotSessionRequest

class PostBotEventTempRequest(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    TypeValue = typing___NewType('TypeValue', builtin___int)
    type___TypeValue = TypeValue
    Type: _Type
    class _Type(google___protobuf___internal___enum_type_wrapper____EnumTypeWrapper[PostBotEventTempRequest.TypeValue]):
        DESCRIPTOR: google___protobuf___descriptor___EnumDescriptor = ...
        UNSPECIFIED = typing___cast(PostBotEventTempRequest.TypeValue, 0)
        INFO = typing___cast(PostBotEventTempRequest.TypeValue, 1)
        ERROR = typing___cast(PostBotEventTempRequest.TypeValue, 2)
    UNSPECIFIED = typing___cast(PostBotEventTempRequest.TypeValue, 0)
    INFO = typing___cast(PostBotEventTempRequest.TypeValue, 1)
    ERROR = typing___cast(PostBotEventTempRequest.TypeValue, 2)
    type___Type = Type

    name: typing___Text = ...
    type: type___PostBotEventTempRequest.TypeValue = ...
    msg: typing___Text = ...

    def __init__(self,
        *,
        name : typing___Optional[typing___Text] = None,
        type : typing___Optional[type___PostBotEventTempRequest.TypeValue] = None,
        msg : typing___Optional[typing___Text] = None,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"msg",b"msg",u"name",b"name",u"type",b"type"]) -> None: ...
type___PostBotEventTempRequest = PostBotEventTempRequest
