# @generated by generate_proto_mypy_stubs.py.  Do not edit!
import sys
from google.protobuf.any_pb2 import (
    Any as google___protobuf___any_pb2___Any,
)

from google.protobuf.descriptor import (
    Descriptor as google___protobuf___descriptor___Descriptor,
    FileDescriptor as google___protobuf___descriptor___FileDescriptor,
)

from google.protobuf.duration_pb2 import (
    Duration as google___protobuf___duration_pb2___Duration,
)

from google.protobuf.internal.containers import (
    RepeatedCompositeFieldContainer as google___protobuf___internal___containers___RepeatedCompositeFieldContainer,
    RepeatedScalarFieldContainer as google___protobuf___internal___containers___RepeatedScalarFieldContainer,
)

from google.protobuf.message import (
    Message as google___protobuf___message___Message,
)

from buildgrid._protos.google.rpc.status_pb2 import (
    Status as google___rpc___status_pb2___Status,
)

from typing import (
    Iterable as typing___Iterable,
    Optional as typing___Optional,
    Text as typing___Text,
)

from typing_extensions import (
    Literal as typing_extensions___Literal,
)


builtin___bool = bool
builtin___bytes = bytes
builtin___float = float
builtin___int = int


DESCRIPTOR: google___protobuf___descriptor___FileDescriptor = ...

class CommandTask(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    class Inputs(google___protobuf___message___Message):
        DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
        class EnvironmentVariable(google___protobuf___message___Message):
            DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
            name: typing___Text = ...
            value: typing___Text = ...

            def __init__(self,
                *,
                name : typing___Optional[typing___Text] = None,
                value : typing___Optional[typing___Text] = None,
                ) -> None: ...
            def ClearField(self, field_name: typing_extensions___Literal[u"name",b"name",u"value",b"value"]) -> None: ...
        type___EnvironmentVariable = EnvironmentVariable

        arguments: google___protobuf___internal___containers___RepeatedScalarFieldContainer[typing___Text] = ...

        @property
        def files(self) -> google___protobuf___internal___containers___RepeatedCompositeFieldContainer[type___Digest]: ...

        @property
        def environment_variables(self) -> google___protobuf___internal___containers___RepeatedCompositeFieldContainer[type___CommandTask.Inputs.EnvironmentVariable]: ...

        def __init__(self,
            *,
            arguments : typing___Optional[typing___Iterable[typing___Text]] = None,
            files : typing___Optional[typing___Iterable[type___Digest]] = None,
            environment_variables : typing___Optional[typing___Iterable[type___CommandTask.Inputs.EnvironmentVariable]] = None,
            ) -> None: ...
        def ClearField(self, field_name: typing_extensions___Literal[u"arguments",b"arguments",u"environment_variables",b"environment_variables",u"files",b"files"]) -> None: ...
    type___Inputs = Inputs

    class Outputs(google___protobuf___message___Message):
        DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
        files: google___protobuf___internal___containers___RepeatedScalarFieldContainer[typing___Text] = ...
        directories: google___protobuf___internal___containers___RepeatedScalarFieldContainer[typing___Text] = ...
        stdout_destination: typing___Text = ...
        stderr_destination: typing___Text = ...

        def __init__(self,
            *,
            files : typing___Optional[typing___Iterable[typing___Text]] = None,
            directories : typing___Optional[typing___Iterable[typing___Text]] = None,
            stdout_destination : typing___Optional[typing___Text] = None,
            stderr_destination : typing___Optional[typing___Text] = None,
            ) -> None: ...
        def ClearField(self, field_name: typing_extensions___Literal[u"directories",b"directories",u"files",b"files",u"stderr_destination",b"stderr_destination",u"stdout_destination",b"stdout_destination"]) -> None: ...
    type___Outputs = Outputs

    class Timeouts(google___protobuf___message___Message):
        DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...

        @property
        def execution(self) -> google___protobuf___duration_pb2___Duration: ...

        @property
        def idle(self) -> google___protobuf___duration_pb2___Duration: ...

        @property
        def shutdown(self) -> google___protobuf___duration_pb2___Duration: ...

        def __init__(self,
            *,
            execution : typing___Optional[google___protobuf___duration_pb2___Duration] = None,
            idle : typing___Optional[google___protobuf___duration_pb2___Duration] = None,
            shutdown : typing___Optional[google___protobuf___duration_pb2___Duration] = None,
            ) -> None: ...
        def HasField(self, field_name: typing_extensions___Literal[u"execution",b"execution",u"idle",b"idle",u"shutdown",b"shutdown"]) -> builtin___bool: ...
        def ClearField(self, field_name: typing_extensions___Literal[u"execution",b"execution",u"idle",b"idle",u"shutdown",b"shutdown"]) -> None: ...
    type___Timeouts = Timeouts


    @property
    def inputs(self) -> type___CommandTask.Inputs: ...

    @property
    def expected_outputs(self) -> type___CommandTask.Outputs: ...

    @property
    def timeouts(self) -> type___CommandTask.Timeouts: ...

    def __init__(self,
        *,
        inputs : typing___Optional[type___CommandTask.Inputs] = None,
        expected_outputs : typing___Optional[type___CommandTask.Outputs] = None,
        timeouts : typing___Optional[type___CommandTask.Timeouts] = None,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions___Literal[u"expected_outputs",b"expected_outputs",u"inputs",b"inputs",u"timeouts",b"timeouts"]) -> builtin___bool: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"expected_outputs",b"expected_outputs",u"inputs",b"inputs",u"timeouts",b"timeouts"]) -> None: ...
type___CommandTask = CommandTask

class CommandOutputs(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    exit_code: builtin___int = ...

    @property
    def outputs(self) -> type___Digest: ...

    def __init__(self,
        *,
        exit_code : typing___Optional[builtin___int] = None,
        outputs : typing___Optional[type___Digest] = None,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions___Literal[u"outputs",b"outputs"]) -> builtin___bool: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"exit_code",b"exit_code",u"outputs",b"outputs"]) -> None: ...
type___CommandOutputs = CommandOutputs

class CommandOverhead(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...

    @property
    def duration(self) -> google___protobuf___duration_pb2___Duration: ...

    @property
    def overhead(self) -> google___protobuf___duration_pb2___Duration: ...

    def __init__(self,
        *,
        duration : typing___Optional[google___protobuf___duration_pb2___Duration] = None,
        overhead : typing___Optional[google___protobuf___duration_pb2___Duration] = None,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions___Literal[u"duration",b"duration",u"overhead",b"overhead"]) -> builtin___bool: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"duration",b"duration",u"overhead",b"overhead"]) -> None: ...
type___CommandOverhead = CommandOverhead

class CommandResult(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    exit_code: builtin___int = ...

    @property
    def status(self) -> google___rpc___status_pb2___Status: ...

    @property
    def outputs(self) -> type___Digest: ...

    @property
    def duration(self) -> google___protobuf___duration_pb2___Duration: ...

    @property
    def overhead(self) -> google___protobuf___duration_pb2___Duration: ...

    @property
    def statistics(self) -> google___protobuf___internal___containers___RepeatedCompositeFieldContainer[google___protobuf___any_pb2___Any]: ...

    def __init__(self,
        *,
        status : typing___Optional[google___rpc___status_pb2___Status] = None,
        exit_code : typing___Optional[builtin___int] = None,
        outputs : typing___Optional[type___Digest] = None,
        duration : typing___Optional[google___protobuf___duration_pb2___Duration] = None,
        overhead : typing___Optional[google___protobuf___duration_pb2___Duration] = None,
        statistics : typing___Optional[typing___Iterable[google___protobuf___any_pb2___Any]] = None,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions___Literal[u"duration",b"duration",u"outputs",b"outputs",u"overhead",b"overhead",u"status",b"status"]) -> builtin___bool: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"duration",b"duration",u"exit_code",b"exit_code",u"outputs",b"outputs",u"overhead",b"overhead",u"statistics",b"statistics",u"status",b"status"]) -> None: ...
type___CommandResult = CommandResult

class FileMetadata(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    path: typing___Text = ...
    contents: builtin___bytes = ...
    is_executable: builtin___bool = ...

    @property
    def digest(self) -> type___Digest: ...

    def __init__(self,
        *,
        path : typing___Optional[typing___Text] = None,
        digest : typing___Optional[type___Digest] = None,
        contents : typing___Optional[builtin___bytes] = None,
        is_executable : typing___Optional[builtin___bool] = None,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions___Literal[u"digest",b"digest"]) -> builtin___bool: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"contents",b"contents",u"digest",b"digest",u"is_executable",b"is_executable",u"path",b"path"]) -> None: ...
type___FileMetadata = FileMetadata

class DirectoryMetadata(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    path: typing___Text = ...

    @property
    def digest(self) -> type___Digest: ...

    def __init__(self,
        *,
        path : typing___Optional[typing___Text] = None,
        digest : typing___Optional[type___Digest] = None,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions___Literal[u"digest",b"digest"]) -> builtin___bool: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"digest",b"digest",u"path",b"path"]) -> None: ...
type___DirectoryMetadata = DirectoryMetadata

class Digest(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    hash: typing___Text = ...
    size_bytes: builtin___int = ...

    def __init__(self,
        *,
        hash : typing___Optional[typing___Text] = None,
        size_bytes : typing___Optional[builtin___int] = None,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"hash",b"hash",u"size_bytes",b"size_bytes"]) -> None: ...
type___Digest = Digest

class Directory(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...

    @property
    def files(self) -> google___protobuf___internal___containers___RepeatedCompositeFieldContainer[type___FileMetadata]: ...

    @property
    def directories(self) -> google___protobuf___internal___containers___RepeatedCompositeFieldContainer[type___DirectoryMetadata]: ...

    def __init__(self,
        *,
        files : typing___Optional[typing___Iterable[type___FileMetadata]] = None,
        directories : typing___Optional[typing___Iterable[type___DirectoryMetadata]] = None,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"directories",b"directories",u"files",b"files"]) -> None: ...
type___Directory = Directory
