# @generated by generate_proto_mypy_stubs.py.  Do not edit!
import sys
from google.protobuf.descriptor import (
    Descriptor as google___protobuf___descriptor___Descriptor,
    FileDescriptor as google___protobuf___descriptor___FileDescriptor,
)

from google.protobuf.message import (
    Message as google___protobuf___message___Message,
)

from typing import (
    Optional as typing___Optional,
    Text as typing___Text,
)

from typing_extensions import (
    Literal as typing_extensions___Literal,
)


builtin___bool = bool
builtin___bytes = bytes
builtin___float = float
builtin___int = int


DESCRIPTOR: google___protobuf___descriptor___FileDescriptor = ...

class ReadRequest(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    resource_name: typing___Text = ...
    read_offset: builtin___int = ...
    read_limit: builtin___int = ...

    def __init__(self,
        *,
        resource_name : typing___Optional[typing___Text] = None,
        read_offset : typing___Optional[builtin___int] = None,
        read_limit : typing___Optional[builtin___int] = None,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"read_limit",b"read_limit",u"read_offset",b"read_offset",u"resource_name",b"resource_name"]) -> None: ...
type___ReadRequest = ReadRequest

class ReadResponse(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    data: builtin___bytes = ...

    def __init__(self,
        *,
        data : typing___Optional[builtin___bytes] = None,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"data",b"data"]) -> None: ...
type___ReadResponse = ReadResponse

class WriteRequest(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    resource_name: typing___Text = ...
    write_offset: builtin___int = ...
    finish_write: builtin___bool = ...
    data: builtin___bytes = ...

    def __init__(self,
        *,
        resource_name : typing___Optional[typing___Text] = None,
        write_offset : typing___Optional[builtin___int] = None,
        finish_write : typing___Optional[builtin___bool] = None,
        data : typing___Optional[builtin___bytes] = None,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"data",b"data",u"finish_write",b"finish_write",u"resource_name",b"resource_name",u"write_offset",b"write_offset"]) -> None: ...
type___WriteRequest = WriteRequest

class WriteResponse(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    committed_size: builtin___int = ...

    def __init__(self,
        *,
        committed_size : typing___Optional[builtin___int] = None,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"committed_size",b"committed_size"]) -> None: ...
type___WriteResponse = WriteResponse

class QueryWriteStatusRequest(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    resource_name: typing___Text = ...

    def __init__(self,
        *,
        resource_name : typing___Optional[typing___Text] = None,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"resource_name",b"resource_name"]) -> None: ...
type___QueryWriteStatusRequest = QueryWriteStatusRequest

class QueryWriteStatusResponse(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    committed_size: builtin___int = ...
    complete: builtin___bool = ...

    def __init__(self,
        *,
        committed_size : typing___Optional[builtin___int] = None,
        complete : typing___Optional[builtin___bool] = None,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"committed_size",b"committed_size",u"complete",b"complete"]) -> None: ...
type___QueryWriteStatusResponse = QueryWriteStatusResponse
