# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: buildgrid/v2/messaging.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from buildgrid._protos.build.bazel.remote.execution.v2 import remote_execution_pb2 as build_dot_bazel_dot_remote_dot_execution_dot_v2_dot_remote__execution__pb2
from buildgrid._protos.google.longrunning import operations_pb2 as google_dot_longrunning_dot_operations__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='buildgrid/v2/messaging.proto',
  package='buildgrid.v2',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x1c\x62uildgrid/v2/messaging.proto\x12\x0c\x62uildgrid.v2\x1a\x36\x62uild/bazel/remote/execution/v2/remote_execution.proto\x1a#google/longrunning/operations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"N\n\x03Job\x12\x0e\n\x06job_id\x18\x01 \x01(\t\x12\x37\n\x06\x61\x63tion\x18\x02 \x01(\x0b\x32\'.build.bazel.remote.execution.v2.Action\"\x87\x02\n\x0f\x43reateOperation\x12\x0e\n\x06job_id\x18\x01 \x01(\t\x12\x16\n\x0eoperation_name\x18\x02 \x01(\t\x12>\n\raction_digest\x18\x03 \x01(\x0b\x32\'.build.bazel.remote.execution.v2.Digest\x12\x11\n\tcacheable\x18\x04 \x01(\x08\x12-\n\ttimestamp\x18\x05 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12J\n\x10request_metadata\x18\x06 \x01(\x0b\x32\x30.build.bazel.remote.execution.v2.RequestMetadata\"\x9c\x01\n\x10UpdateOperations\x12\x0e\n\x06job_id\x18\x01 \x01(\t\x12\x36\n\x0foperation_state\x18\x02 \x01(\x0b\x32\x1d.google.longrunning.Operation\x12\x11\n\tcacheable\x18\x03 \x01(\x08\x12-\n\ttimestamp\x18\x04 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"l\n\x0cRetryableJob\x12\x0e\n\x06job_id\x18\x01 \x01(\t\x12\x37\n\x06\x61\x63tion\x18\x02 \x01(\x0b\x32\'.build.bazel.remote.execution.v2.Action\x12\x13\n\x0brouting_key\x18\x03 \x01(\t\"\x88\x01\n\tBotStatus\x12\x10\n\x08\x62ot_name\x18\x01 \x01(\t\x12/\n\x0b\x61ssignments\x18\x02 \x03(\x0b\x32\x1a.buildgrid.v2.RetryableJob\x12\x38\n\x14\x63onnection_timestamp\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.Timestampb\x06proto3'
  ,
  dependencies=[build_dot_bazel_dot_remote_dot_execution_dot_v2_dot_remote__execution__pb2.DESCRIPTOR,google_dot_longrunning_dot_operations__pb2.DESCRIPTOR,google_dot_protobuf_dot_timestamp__pb2.DESCRIPTOR,])




_JOB = _descriptor.Descriptor(
  name='Job',
  full_name='buildgrid.v2.Job',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='job_id', full_name='buildgrid.v2.Job.job_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='action', full_name='buildgrid.v2.Job.action', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=172,
  serialized_end=250,
)


_CREATEOPERATION = _descriptor.Descriptor(
  name='CreateOperation',
  full_name='buildgrid.v2.CreateOperation',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='job_id', full_name='buildgrid.v2.CreateOperation.job_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='operation_name', full_name='buildgrid.v2.CreateOperation.operation_name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='action_digest', full_name='buildgrid.v2.CreateOperation.action_digest', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='cacheable', full_name='buildgrid.v2.CreateOperation.cacheable', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='buildgrid.v2.CreateOperation.timestamp', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='request_metadata', full_name='buildgrid.v2.CreateOperation.request_metadata', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=253,
  serialized_end=516,
)


_UPDATEOPERATIONS = _descriptor.Descriptor(
  name='UpdateOperations',
  full_name='buildgrid.v2.UpdateOperations',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='job_id', full_name='buildgrid.v2.UpdateOperations.job_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='operation_state', full_name='buildgrid.v2.UpdateOperations.operation_state', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='cacheable', full_name='buildgrid.v2.UpdateOperations.cacheable', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='buildgrid.v2.UpdateOperations.timestamp', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=519,
  serialized_end=675,
)


_RETRYABLEJOB = _descriptor.Descriptor(
  name='RetryableJob',
  full_name='buildgrid.v2.RetryableJob',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='job_id', full_name='buildgrid.v2.RetryableJob.job_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='action', full_name='buildgrid.v2.RetryableJob.action', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='routing_key', full_name='buildgrid.v2.RetryableJob.routing_key', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=677,
  serialized_end=785,
)


_BOTSTATUS = _descriptor.Descriptor(
  name='BotStatus',
  full_name='buildgrid.v2.BotStatus',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='bot_name', full_name='buildgrid.v2.BotStatus.bot_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='assignments', full_name='buildgrid.v2.BotStatus.assignments', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='connection_timestamp', full_name='buildgrid.v2.BotStatus.connection_timestamp', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=788,
  serialized_end=924,
)

_JOB.fields_by_name['action'].message_type = build_dot_bazel_dot_remote_dot_execution_dot_v2_dot_remote__execution__pb2._ACTION
_CREATEOPERATION.fields_by_name['action_digest'].message_type = build_dot_bazel_dot_remote_dot_execution_dot_v2_dot_remote__execution__pb2._DIGEST
_CREATEOPERATION.fields_by_name['timestamp'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_CREATEOPERATION.fields_by_name['request_metadata'].message_type = build_dot_bazel_dot_remote_dot_execution_dot_v2_dot_remote__execution__pb2._REQUESTMETADATA
_UPDATEOPERATIONS.fields_by_name['operation_state'].message_type = google_dot_longrunning_dot_operations__pb2._OPERATION
_UPDATEOPERATIONS.fields_by_name['timestamp'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_RETRYABLEJOB.fields_by_name['action'].message_type = build_dot_bazel_dot_remote_dot_execution_dot_v2_dot_remote__execution__pb2._ACTION
_BOTSTATUS.fields_by_name['assignments'].message_type = _RETRYABLEJOB
_BOTSTATUS.fields_by_name['connection_timestamp'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
DESCRIPTOR.message_types_by_name['Job'] = _JOB
DESCRIPTOR.message_types_by_name['CreateOperation'] = _CREATEOPERATION
DESCRIPTOR.message_types_by_name['UpdateOperations'] = _UPDATEOPERATIONS
DESCRIPTOR.message_types_by_name['RetryableJob'] = _RETRYABLEJOB
DESCRIPTOR.message_types_by_name['BotStatus'] = _BOTSTATUS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Job = _reflection.GeneratedProtocolMessageType('Job', (_message.Message,), {
  'DESCRIPTOR' : _JOB,
  '__module__' : 'buildgrid.v2.messaging_pb2'
  # @@protoc_insertion_point(class_scope:buildgrid.v2.Job)
  })
_sym_db.RegisterMessage(Job)

CreateOperation = _reflection.GeneratedProtocolMessageType('CreateOperation', (_message.Message,), {
  'DESCRIPTOR' : _CREATEOPERATION,
  '__module__' : 'buildgrid.v2.messaging_pb2'
  # @@protoc_insertion_point(class_scope:buildgrid.v2.CreateOperation)
  })
_sym_db.RegisterMessage(CreateOperation)

UpdateOperations = _reflection.GeneratedProtocolMessageType('UpdateOperations', (_message.Message,), {
  'DESCRIPTOR' : _UPDATEOPERATIONS,
  '__module__' : 'buildgrid.v2.messaging_pb2'
  # @@protoc_insertion_point(class_scope:buildgrid.v2.UpdateOperations)
  })
_sym_db.RegisterMessage(UpdateOperations)

RetryableJob = _reflection.GeneratedProtocolMessageType('RetryableJob', (_message.Message,), {
  'DESCRIPTOR' : _RETRYABLEJOB,
  '__module__' : 'buildgrid.v2.messaging_pb2'
  # @@protoc_insertion_point(class_scope:buildgrid.v2.RetryableJob)
  })
_sym_db.RegisterMessage(RetryableJob)

BotStatus = _reflection.GeneratedProtocolMessageType('BotStatus', (_message.Message,), {
  'DESCRIPTOR' : _BOTSTATUS,
  '__module__' : 'buildgrid.v2.messaging_pb2'
  # @@protoc_insertion_point(class_scope:buildgrid.v2.BotStatus)
  })
_sym_db.RegisterMessage(BotStatus)


# @@protoc_insertion_point(module_scope)
