# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: buildgrid/v2/query_build_events.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from buildgrid._protos.google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2
from buildgrid._protos.google.devtools.build.v1 import build_events_pb2 as google_dot_devtools_dot_build_dot_v1_dot_build__events__pb2
from buildgrid._protos.google.devtools.build.v1 import publish_build_event_pb2 as google_dot_devtools_dot_build_dot_v1_dot_publish__build__event__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='buildgrid/v2/query_build_events.proto',
  package='buildgrid.v2',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n%buildgrid/v2/query_build_events.proto\x12\x0c\x62uildgrid.v2\x1a\x1cgoogle/api/annotations.proto\x1a+google/devtools/build/v1/build_events.proto\x1a\x32google/devtools/build/v1/publish_build_event.proto\"4\n\x18QueryEventStreamsRequest\x12\x18\n\x10\x62uild_id_pattern\x18\x01 \x01(\t\"\xef\x01\n\x19QueryEventStreamsResponse\x12I\n\x07streams\x18\x01 \x03(\x0b\x32\x38.buildgrid.v2.QueryEventStreamsResponse.BuildEventStream\x1a\x86\x01\n\x10\x42uildEventStream\x12\x35\n\tstream_id\x18\x01 \x01(\x0b\x32\".google.devtools.build.v1.StreamId\x12;\n\x06\x65vents\x18\x02 \x03(\x0b\x32+.google.devtools.build.v1.OrderedBuildEvent2\x9b\x01\n\x10QueryBuildEvents\x12\x86\x01\n\x11QueryEventStreams\x12&.buildgrid.v2.QueryEventStreamsRequest\x1a\'.buildgrid.v2.QueryEventStreamsResponse\" \x82\xd3\xe4\x93\x02\x1a\x12\x18/v1/{name=event_streams}b\x06proto3'
  ,
  dependencies=[google_dot_api_dot_annotations__pb2.DESCRIPTOR,google_dot_devtools_dot_build_dot_v1_dot_build__events__pb2.DESCRIPTOR,google_dot_devtools_dot_build_dot_v1_dot_publish__build__event__pb2.DESCRIPTOR,])




_QUERYEVENTSTREAMSREQUEST = _descriptor.Descriptor(
  name='QueryEventStreamsRequest',
  full_name='buildgrid.v2.QueryEventStreamsRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='build_id_pattern', full_name='buildgrid.v2.QueryEventStreamsRequest.build_id_pattern', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=182,
  serialized_end=234,
)


_QUERYEVENTSTREAMSRESPONSE_BUILDEVENTSTREAM = _descriptor.Descriptor(
  name='BuildEventStream',
  full_name='buildgrid.v2.QueryEventStreamsResponse.BuildEventStream',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='stream_id', full_name='buildgrid.v2.QueryEventStreamsResponse.BuildEventStream.stream_id', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='events', full_name='buildgrid.v2.QueryEventStreamsResponse.BuildEventStream.events', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=342,
  serialized_end=476,
)

_QUERYEVENTSTREAMSRESPONSE = _descriptor.Descriptor(
  name='QueryEventStreamsResponse',
  full_name='buildgrid.v2.QueryEventStreamsResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='streams', full_name='buildgrid.v2.QueryEventStreamsResponse.streams', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_QUERYEVENTSTREAMSRESPONSE_BUILDEVENTSTREAM, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=237,
  serialized_end=476,
)

_QUERYEVENTSTREAMSRESPONSE_BUILDEVENTSTREAM.fields_by_name['stream_id'].message_type = google_dot_devtools_dot_build_dot_v1_dot_build__events__pb2._STREAMID
_QUERYEVENTSTREAMSRESPONSE_BUILDEVENTSTREAM.fields_by_name['events'].message_type = google_dot_devtools_dot_build_dot_v1_dot_publish__build__event__pb2._ORDEREDBUILDEVENT
_QUERYEVENTSTREAMSRESPONSE_BUILDEVENTSTREAM.containing_type = _QUERYEVENTSTREAMSRESPONSE
_QUERYEVENTSTREAMSRESPONSE.fields_by_name['streams'].message_type = _QUERYEVENTSTREAMSRESPONSE_BUILDEVENTSTREAM
DESCRIPTOR.message_types_by_name['QueryEventStreamsRequest'] = _QUERYEVENTSTREAMSREQUEST
DESCRIPTOR.message_types_by_name['QueryEventStreamsResponse'] = _QUERYEVENTSTREAMSRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

QueryEventStreamsRequest = _reflection.GeneratedProtocolMessageType('QueryEventStreamsRequest', (_message.Message,), {
  'DESCRIPTOR' : _QUERYEVENTSTREAMSREQUEST,
  '__module__' : 'buildgrid.v2.query_build_events_pb2'
  # @@protoc_insertion_point(class_scope:buildgrid.v2.QueryEventStreamsRequest)
  })
_sym_db.RegisterMessage(QueryEventStreamsRequest)

QueryEventStreamsResponse = _reflection.GeneratedProtocolMessageType('QueryEventStreamsResponse', (_message.Message,), {

  'BuildEventStream' : _reflection.GeneratedProtocolMessageType('BuildEventStream', (_message.Message,), {
    'DESCRIPTOR' : _QUERYEVENTSTREAMSRESPONSE_BUILDEVENTSTREAM,
    '__module__' : 'buildgrid.v2.query_build_events_pb2'
    # @@protoc_insertion_point(class_scope:buildgrid.v2.QueryEventStreamsResponse.BuildEventStream)
    })
  ,
  'DESCRIPTOR' : _QUERYEVENTSTREAMSRESPONSE,
  '__module__' : 'buildgrid.v2.query_build_events_pb2'
  # @@protoc_insertion_point(class_scope:buildgrid.v2.QueryEventStreamsResponse)
  })
_sym_db.RegisterMessage(QueryEventStreamsResponse)
_sym_db.RegisterMessage(QueryEventStreamsResponse.BuildEventStream)



_QUERYBUILDEVENTS = _descriptor.ServiceDescriptor(
  name='QueryBuildEvents',
  full_name='buildgrid.v2.QueryBuildEvents',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=479,
  serialized_end=634,
  methods=[
  _descriptor.MethodDescriptor(
    name='QueryEventStreams',
    full_name='buildgrid.v2.QueryBuildEvents.QueryEventStreams',
    index=0,
    containing_service=None,
    input_type=_QUERYEVENTSTREAMSREQUEST,
    output_type=_QUERYEVENTSTREAMSRESPONSE,
    serialized_options=b'\202\323\344\223\002\032\022\030/v1/{name=event_streams}',
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_QUERYBUILDEVENTS)

DESCRIPTOR.services_by_name['QueryBuildEvents'] = _QUERYBUILDEVENTS

# @@protoc_insertion_point(module_scope)
