"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import typing
import typing_extensions

import buildgrid._protos.google.devtools.build.v1.build_events_pb2
import buildgrid._protos.google.devtools.build.v1.publish_build_event_pb2

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor = ...

class QueryEventStreamsRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    BUILD_ID_PATTERN_FIELD_NUMBER: builtins.int
    build_id_pattern: typing.Text = ...

    def __init__(self,
        *,
        build_id_pattern : typing.Text = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"build_id_pattern",b"build_id_pattern"]) -> None: ...
global___QueryEventStreamsRequest = QueryEventStreamsRequest

class QueryEventStreamsResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    class BuildEventStream(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
        STREAM_ID_FIELD_NUMBER: builtins.int
        EVENTS_FIELD_NUMBER: builtins.int

        @property
        def stream_id(self) -> buildgrid._protos.google.devtools.build.v1.build_events_pb2.StreamId: ...

        @property
        def events(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[buildgrid._protos.google.devtools.build.v1.publish_build_event_pb2.OrderedBuildEvent]: ...

        def __init__(self,
            *,
            stream_id : typing.Optional[buildgrid._protos.google.devtools.build.v1.build_events_pb2.StreamId] = ...,
            events : typing.Optional[typing.Iterable[buildgrid._protos.google.devtools.build.v1.publish_build_event_pb2.OrderedBuildEvent]] = ...,
            ) -> None: ...
        def HasField(self, field_name: typing_extensions.Literal[u"stream_id",b"stream_id"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing_extensions.Literal[u"events",b"events",u"stream_id",b"stream_id"]) -> None: ...

    STREAMS_FIELD_NUMBER: builtins.int

    @property
    def streams(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___QueryEventStreamsResponse.BuildEventStream]: ...

    def __init__(self,
        *,
        streams : typing.Optional[typing.Iterable[global___QueryEventStreamsResponse.BuildEventStream]] = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"streams",b"streams"]) -> None: ...
global___QueryEventStreamsResponse = QueryEventStreamsResponse
